### PR TITLE
Lint issues and test script

### PR DESCRIPTION
**Pull request by vinicius0026**
Hi there.

First of all, thanks to putting your effort into building open source modules!

I'm starting a project with rethinkdb and I think your module will be of great help. But I've seen that it has been stale for a while.

This PR just solve some issues with linter and adds the default npm test script. But I have more things in mind, if you want help advancing this lib.

Well, I'll let you analyse this PR before submitting new things.

### CODE REVIEW

**Comment by jordanh** [comment]
Hi @vinicius0026, we're actively [maintaining a fork](https://github.com/ParabolInc/migrate-rethinkdb). If you'd submit this pull, we'd gladly accept it.

**Comment by vinicius0026** [comment]
Hi @jordanh 
Since there was no answer whatsoever here, I created a [new version](https://github.com/vinicius0026/rethinkdb-migrate) of this tool. As I wanted to update and organize code, I rewrote it from scratch, but it already is at feature parity with the original module.

If you are interested, we could put some joint effort into merging your fork with my re-implementation, so that there is one maintained lib for rethink migrations. What do you think?

**Comment by jordanh** [comment]
I like one over two versions for sure – I remember trying your new fork while you were in the middle of making the transition. I had some difficulty getting it to work on [our codebase].

Would you like to fork our code and give yours a shot again? If it works, we'll switch over!

**Comment by vinicius0026** [comment]
@jordanh I'm not sure I fully understood your last paragraph. But please be welcome to take another look at [rethinkdb-migrate](https://github.com/vinicius0026/rethinkdb-migrate). By now some bugs have been fixed, documentation has improved and there is another active collaborator, besides myself. Your collaboration would be much appreciated.

**Comment by JohanObrink** [comment]
@vinicius0026 Thanks for the PR. Sorry I haven't been active for a while - to much work :(
If you are interested, I can add you as a contributor. I could really need some help. I also asked @jordanh If he wants to merge the fork back in.

**Pull request merged**
